name: advanced_calculator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  math_expressions: ^2.6.0
  provider: ^6.1.2
  sqflite: ^2.4.0
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
